name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Construir APK
        uses: ArtemSBulgakov/buildozer-action@v1

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
